server:
  port: 8094
  servlet:
    context-path: /inventory

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  application:
    name: inventory-service

