global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product_service1'
    metrics_path: '/product/actuator/prometheus'
    static_configs:
#      - targets: ['host.docker.internal:8080']
      - targets: ['product-service1:8093']
        labels:
          application: 'Product Service Application1'
  - job_name: 'product_service2'
    metrics_path: '/product/actuator/prometheus'
    static_configs:
#      - targets: ['host.docker.internal:8080']
      - targets: ['product-service2:8093']
        labels:
          application: 'Product Service Application2'
  - job_name: 'order_service'
    metrics_path: '/order/actuator/prometheus'
    static_configs:
#      - targets: ['host.docker.internal:8080']
      - targets: ['order-service:8092']
        labels:
          application: 'Order Service Application'
  - job_name: 'inventory_service'
    metrics_path: '/inventory/actuator/prometheus'
    static_configs:
#      - targets: ['host.docker.internal:8080']
      - targets: ['inventory-service:8094']
        labels:
          application: 'Inventory Service Application'