apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grafana-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
