eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
spring:
  application:
    name: product-service
#  cache:
#    redis:
#      url : redis://localhost:6379 do not use any of this, not work in docker environment correctly
    #  host: localhost
    #  port: 6379
    #      time-to-live: 100S
#    type: redis

  data:
    redis:
      host: localhost
      port: 6379

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
